package rw.transport.vubaride.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@NoArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String username;
    private String email;
    private String password;

    // Role field - Enum representing user roles (like ADMIN, USER, etc.)
    @Enumerated(EnumType.STRING)
    private Role role;  

    // Token for password reset functionality
    private String resetPasswordToken;

    // Constructors, getters, and setters will be auto-generated by Lombok
}
